### ISSUE TITLE
在标题里放特殊字符存在纵向对不齐

### ISSUE THREAD

**Issue by zpdg** [favourhong/Awesome-Marp#13]
您好，

首先需要感谢您的付出，这个项目非常优秀，帮我节省了不少时间！我目前只发现了一个小问题，不知能否解决，如下：

在标题里放特殊字符存在纵向对不齐。下面是一个例子：
```markdown
<!-- _class: fixedtitleA-->

## $\chi^2$-minimize method

- $\chi^2$-minimize method

$\chi^2$-minimize method
```

预览效果如下: 
![Screenshot from 2023-10-24 15-47-42](https://github.com/favourhong/Awesome-Marp/assets/56651134/eca1267f-38d8-4fad-abfb-8ebd1fd9b500)

可以发现标题里纵向对不齐，正文里要好很多。

我也发现，这似乎是markdown的问题，在obsidian里测试也是这样。我没能理解，也没能在网上找到这个现象的问题根源。目前我的解决方案是加一个\huge去改变字体大小，这样就可以对的很好了。不过，我还是很好奇有没有更好的解决方案。

感谢！

**Comment by favourhong** [comment]
很开心能给你提供到帮助 🤗~
你的问题应该是由于“标题中的数学公式字号比较小”造成的。这个会在下一个版本中更新，你也可以在 CSS 文件中增加以下几行代码：
```css
h2 .MathJax, h3 .MathJax, h4 .MathJax, h3 .MathJax {
  font-size: 1.5rem;
}

h4 .MathJax, h5 .MathJax {
  font-size: 1.2rem;
}
```
