### ISSUE TITLE
有序列表失效

### ISSUE THREAD

**Issue by flysaber** [favourhong/Awesome-Marp#15]
有序列表在幻灯片内失效，请修正。

**Comment by Enoch2090** [comment]
同样问题，使用marp-cli与 obsidian 预览均出现此问题

**Comment by Enoch2090** [comment]
虽然没有完全理解为什么，但是可用的fix：
修改使用的css中 `section.toc_b ul, ol `、`ol`项：

```css
ol {
  line-height: 1.4rem;
  padding-left: 35px;
}

...

section.toc_b ul,
ol {
  display: table;
  align-items: center;
  justify-content: center;
  width: 63%;
  left: 0%;
  position: relative;
  line-height: 200%;
}
```
即可恢复正常的有序列表。
